import Head from 'next/head'
import { useEffect, useState } from 'react'

// Components
import Navigation from 'components/shared/navigation'
import Hero from 'components/sections/hero'
import Panel from 'components/sections/panel'
import Profile from 'components/sections/profile'
import Projects from 'components/sections/projects'
import References from 'components/sections/references'
import Contact from 'components/sections/contact'
import Footer from 'components/shared/footer'


export default function Home() {
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = event => {
      window.scrollY > 300 ? setScrolled(true) : setScrolled(false)
    }

    window.addEventListener('scroll', handleScroll)

    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  }, [setScrolled])

  return (
    <>
      <Head>
        <title>Jiří Šrytr | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/zab6eql.css" />
      </Head>

      <Navigation scrolled={ scrolled } />

      <Hero scrolled={ scrolled } />
      <Panel scrolled={ scrolled } />
      <Profile />
      <Projects />
      <References />
      <Contact />

      <Footer />

    </>
  )
}
